### ISSUE TITLE
准备在实际项目中使用看看，作者有在自己的项目中使用么。

### ISSUE THREAD

**Issue by kaleai** [ragnraok/StaticLayoutView#1]
看到了作者在原文的基础上，自己做了宽、高等优化，希望能持续优化。

**Comment by ragnraok** [comment]
最近正在基于这里的原理开发一套完整的预渲染TextView控件，等开发完成之后估计这里会开源出来哈~

**Comment by kaleai** [comment]
支持，希望开发出来后可以通知一下哈。

**Comment by eling13** [comment]
感谢up主研究预渲染控件。我最近也是在listView中发现如果text里包含span和emoji时，滑动会有卡顿现象。。想问下up主，像评论comment这些多个textview，up主一般用什么来承载它们？用ListView还是layout一个一个addview的？

**Comment by ragnraok** [comment]
@eling13 ListView没有办法完全展开的，一般是用类似LinearLayout这样子，然后一个一个addView加上去

**Comment by eling13** [comment]
@ragnraok 
public void onMeasure(int widthMeasureSpec, int heightMeasureSpec){
         int mExpandSpec = MeasureSpec.makeMeasureSpec(Integer.MAX_VALUE >> 2,         MeasureSpec.AT_MOST);
         super.onMeasure(widthMeasureSpec, mExpandSpec);
    }

网上查找的时候有说listview里嵌套girdview，重写onMeasure，就可以全部展开全部显示girdview。测试了图片倒是能全部展开(九宫图)，但评论就只展开6、7条这样。。

**Comment by eling13** [comment]
@ragnraok 如果真用linearLayout的话，那在getview里是不是每次linearLayout都要removeall啊。。咋配合你这个使用预渲染呢。而且，是不是要监听滑动，StaticLayout[] layout，来开启个背景线程来初始化新的评论

**Comment by eling13** [comment]
还有用这个StaticLayoutView,做span的载体的话，如果想要高亮某个，可点击跳转的话，像点击评论人可以跳转。是不是要重写ontouthEvent了进行判断了？

**Comment by ragnraok** [comment]
@eling13 是的，基本上相当于重造一个TextView

**Comment by eling13** [comment]
@ragnraok 莫名的感觉好难啊，这样搞不知道得花多少时间才搞定。。

**Comment by ragnraok** [comment]
@eling13 其实并不是十分复杂，系统的TextView由于需要估计许多不同的情况而写得十分复杂，像这种情况下的只是一个用StaticLayout的轻量级TextView，把这些逻辑单独抽出来之后其实是非常简单的

另外，你之前遇到的滑动的时候遇到span会卡顿，其实很有可能是在setSpan的时候消耗了大量时间，你可以试下跑traceview验证一下看下哪个阶段消耗的时间很多，推荐只有到measure为瓶颈之后才去使用这里的优化哈~

**Comment by eling13** [comment]
@ragnraok  一般就是在span那里费时了吧，网上有说光是创建和渲染带有span和emoji表情的textview就花费将近80ms了，这时间还是蛮久蛮恐怖的。我再重新想下思路该怎么添加评论textview，up主，期待你的这个预渲染textview啊！

**Comment by kaleai** [comment]
https://github.com/facebookincubator/TextLayoutBuilder @eling13 @ragnraok
